### ISSUE TITLE
Move to init object and store as attribute of the class

### ISSUE THREAD

**Issue by ananas-block** [Shigoto-dev19/ZK-Battleships-Solana#12]
https://github.com/Shigoto-dev19/ZK-Battleships-Solana/blob/6653dee2976ecbdcff0a48529c79a9b5dd4e7685/src/battleShipClient.ts#L76

const boardHash = await mimcSponge.multiHash(board.flat());

should be

const boardHash = await this.mimcSponge.multiHash(board.flat());

**Comment by Shigoto-dev19** [comment]
I solved it as BattleShipClient.mimcSponge because the initialize method is static
