### ISSUE TITLE
Naming is confusing, alice, host, and player one are the same? then name should be the same

### ISSUE THREAD

**Issue by ananas-block** [Shigoto-dev19/ZK-Battleships-Solana#14]
https://github.com/Shigoto-dev19/ZK-Battleships-Solana/blob/6653dee2976ecbdcff0a48529c79a9b5dd4e7685/test/game.test.ts#L60

you can append or prepend if you want.

player1Host idk

**Comment by Shigoto-dev19** [comment]
yea, both namings were to give context
