### ISSUE TITLE
Why is this nested?

### ISSUE THREAD

**Issue by ananas-block** [Shigoto-dev19/ZK-Battleships-Solana#15]
https://github.com/Shigoto-dev19/ZK-Battleships-Solana/blob/6653dee2976ecbdcff0a48529c79a9b5dd4e7685/test/game.test.ts#L106

Your file is just 100 lines long, why nest this test?

It is a lot worse for readability and just another 100 lines

**Comment by Shigoto-dev19** [comment]
do you suggest breaking down the function simulate inside the test?

**Comment by Shigoto-dev19** [comment]
just open up the function to the test case, it is just used once so it makes sense
