### ISSUE TITLE
Oh lol the function is in the same file, I am so confused by this

### ISSUE THREAD

**Issue by ananas-block** [Shigoto-dev19/ZK-Battleships-Solana#17]
https://github.com/Shigoto-dev19/ZK-Battleships-Solana/blob/6653dee2976ecbdcff0a48529c79a9b5dd4e7685/test/game.test.ts#L106

**Comment by Shigoto-dev19** [comment]
the function was written in the beginning and then called inside the test
Ill check the other comment that you replied concerning this matter
