### ISSUE TITLE
Footgun try catch around proof verification

### ISSUE THREAD

**Issue by ananas-block** [Shigoto-dev19/ZK-Battleships-Solana#2]
https://github.com/Shigoto-dev19/ZK-Battleships-Solana/blob/39e42bc8ee11b75b3559b9ad005c97b33dc9baf3/src/gameSimulation.ts#L177

apart from very initial testing you will want this to crash your test or client

**Comment by Shigoto-dev19** [comment]
should i remove try/catch block then ?
