### ISSUE TITLE
Unnessary function

### ISSUE THREAD

**Issue by ananas-block** [Shigoto-dev19/ZK-Battleships-Solana#5]
https://github.com/Shigoto-dev19/ZK-Battleships-Solana/blob/39e42bc8ee11b75b3559b9ad005c97b33dc9baf3/src/utils.ts#L60

**Comment by Shigoto-dev19** [comment]
I wrote this to avoid block-redeclaration errors, when proof and public signals are called in the same block having the same name makes error

**Comment by Shigoto-dev19** [comment]
it is an object result, i tried that even when coding elgamal test. ill try a different solution

**Comment by Shigoto-dev19** [comment]
I am leaving the function, it makes things more clearer and practical, one method is to use proof and public signals as variables and change their values whenever fullprove is called, the names always stay netural, for me it is a matter of two lines that facilitate the fullprove procedure, I started doing what u wrote but i didn't see it useful. If you see that it makes difference, I can do it again
